### ISSUE TITLE
SECURITY error Stripe - oders state

### ISSUE THREAD

**Issue by adamus007p** [202-ecommerce/stripe_official#103]
In my Stripe __ see that some pending payments is checked "Consider the associated order as validated."

This is a big mistake.

Which send order as valid and in my case Prestashop was sending links to download to customers.
Even when the payment was pending.

All pending payments are wrong!!!

Please check and update it guys,

order state logable.

install order state

$order_state->logable = true;
public function installOrderState(

stripe_official.php

In my opinion it is a Prestashop mistake however Stripe.

I believe the same s**it is with other payment modules.

https://zemez.io/support/prestashop/how-to/prestashop-1-7-manage-order-statuses/

**Comment by clotairer** [comment]
@adamus007p 

The issue you describe seems link to a feature/parameter of PretaShop that consider an order as validated (paid) even if it's not enough the case. 
According to the doc : https://doc.prestashop.com/display/PS17/Statuses "If enabled, this status marks all associated orders as "paid", and puts them in this same status."

Could you tell me if all your pending orders are automatically validated or only associated orders ?
On witch version of PrestaShop do you have this issue ? Do you have published an issue on PrestaShop Github ? 
It will be interesting to receive helps from PrestaShop. Perhaps the bug is already registered...

**Comment by clotairer** [comment]
Without response since last week, I close this ticket.

If you need help from our technical team, please contact our support on this form 
https://addons.prestashop.com/en/contact-us?id_product=24922

Thank you.
