### ISSUE TITLE
Add a test if file exist or not overrided

### ISSUE THREAD

**Issue by carlead** [202-ecommerce/stripe_official#131]
Hello,

If we want to add an action class in a classes override folder this does not work because we do not add it in the base folder of the module to do things properly.

Example :
Addition of the ExampleActions.php file in src/override/modules/stripe_official/classes/actions/ExampleActions.php

You should test if the file exists otherwise test if it is not in a folder the override

https://github.com/202-ecommerce/stripe_official/blob/1c7086d8941bbdc89c4ed14dbef6cc8dd9552b0b/vendor/totpsclasslib/src/Actions/ActionsHandler.php#L128

**Comment by clotairer** [comment]
Hi,

We recommend to use hook actionStripe_officialActionsHandler to defined your own class (eventually extend the default action class) instead of an override.

https://github.com/202-ecommerce/stripe_official/blob/1c7086d8941bbdc89c4ed14dbef6cc8dd9552b0b/vendor/totpsclasslib/src/Actions/ActionsHandler.php#L139

(I've never check a hook with _ ...)
