### ISSUE TITLE
bancontact error payment intent capture only automatic

### ISSUE THREAD

**Issue by darkstudio** [202-ecommerce/stripe_official#147]
Hi,
Prestashop 1.7.5.6
PHP 7.3
Stripe 2.3.1

I have already mention this bug bug i am always stuck since many month in version 2.3.1 of stripe module.
When we update on any version after 2.3.1 (i have just tried 2.4.3), we have a error message on last step.
To avoid make reccurent problem on the live website, we have clone the prestashop localy to make tests.

**Comment by clotairer** [comment]
Thank you for your report.

Could you please install the module stripe_wizard as https://github.com/202-ecommerce/stripe_official/issues/115#issuecomment-1088555510 ? 
We develop this module to analyze and fix hooks not plugged, statuses and improper configurations that are not available on the module.

You probably have a miss configuration due to an upgrade.

**Comment by clotairer** [comment]
You don't have this line on your module ? 

https://github.com/202-ecommerce/stripe_official/blob/5631793cf2e3645440ccd2494a0ca431f0615225/stripe_official.php#L99

**Comment by clotairer** [comment]
Hi,

We reproduce the scenario.
1. Try to pay by card with an error (without change of page).
2. Try to pay by Bancontact.
3. See the error

We will inform you when a fix will be found.

**Comment by clotairer** [comment]
Hi @darkstudio 

We work on a fix. The bug was if a payment intent is created for a direct payment with automatic capture, this payment intent can't be updated by the Stripe SDK with an other capture method (bancantact have its own behaviour of capture).

If you have the opportunity to try the PR before we publish the release 2.4.5, it will be nice for us to get your feedback. If not, we could inform you when we publish the next Pre-Release.

Have a good day.
