### ISSUE TITLE
Hi I cant pay by stripe with testdata

### ISSUE THREAD

**Issue by shmidtelson** [202-ecommerce/stripe_official#196]
website https://sift.ro/ 
Form just reload after send. 
Do you have any ideas what i can do?
Plugin 2.4.6.
prestashop 1.7.8.7

**Comment by clotairer** [comment]
Hi, 
It looks like you use a one page checkout. There is some trouble with OPC modules. They need to define the frotn controller name with this hook :  
https://github.com/202-ecommerce/stripe_official/blob/68afd0fb546f45868bd28ed47928898952e5522a/stripe_official.php#L1661

If your OPC controller dosn't load JS of Stripe. That's why payment form is not loaded.

**Comment by shmidtelson** [comment]
![2022-11-23_14-53](https://user-images.githubusercontent.com/6944443/203540464-0c66ecb3-7a13-45b3-8ee3-54314f82b9ef.png)
Looks that it  should work

**Comment by shmidtelson** [comment]
![image](https://user-images.githubusercontent.com/6944443/203541152-67894857-1156-4649-aeff-42c021e8c136.png)
Stripe.js exists :thinking:

**Comment by shmidtelson** [comment]
Form exists but after press button pay - just reload page

**Comment by clotairer** [comment]
The issue is probably due to ajax loding of your OPC module. The JS variable and stripe JS is perhaps not evaled in the ajax content.

**Comment by shmidtelson** [comment]
Ok! Probably that is the problem in theme of site? right?
