### ISSUE TITLE
No more multistore support starting with 2.3.5 ???

### ISSUE THREAD

**Issue by Chrisi1321** [202-ecommerce/stripe_official#77]
I have big issues with the stripe module in the current version 2.3.5 and your support from prestashop addons told me that it is not possible anymore with 2.3.5 to support multistore core feature of prestashop. Is this true?
My config is the following.

I have 3 domains 

abcabc.at
abcabc.de
abcabc.ch

Each domain has it's own stripe account. As I have 3 different credentials I always chose the shop/domain in the backoffice and set the credentials for the shop. 
Nice and easy, no worries until now.... 

It all started with the issue that payments from only from abcabc.at were captured. With another update the orders from the  domains abcabc.de and abcabc.ch were also not captured and after placing an test order you get always redirected to your account with your order history, but no order confirmation. In the background the order still seems to be some kind of validated because I can see this in the stripe dashboard.

Any ideas or help??

**Comment by Ashley-Butcher** [comment]
Having a similar issue to this. I have two other multistore issues:

 - Per store, we see the error "Webhook configuration cannot be accessed, click on save button to fix issue. A new webhook will be created on Stripe." when configuring the Stripe module. If we click save to fix it, it works, but only for that store. If we click "save" in another store context, then it's fixed only for THAT store now, and the other previous store again shows a setup problem.

 - If showing the card logos is enabled for multiple stores (i.e. VISA would be selected for 5 stores) then on every store, selected or not, *five* VISA logos are shown. We have since disabled this in the configuration so our shop doesn't look scammy, as having multiple credit card logos one after the other in a big block looks really dodgy and doesn't inspire confidence.

One other thing that might be related, see also [issue 80](https://github.com/202-ecommerce/stripe_official/issues/80).

**Comment by mribeiro202** [comment]
Hi everyone,

Have you tried to install the new version of module 2.3.6?
This is a known problem with 2.3.5 that has been solved in 2.3.6. I recommend that you install this version.

Have a nice day

**Comment by Ashley-Butcher** [comment]
Update: Seems like issue #93 is related here too as it's the same symptoms. We're running 2.3.6 in a multistore environment too and it seems like the webhooks fail. Customers see their orders are placed, but cart becomes abandoned, webhook from Stripe to PrestaShop fails (doesn't seem to be able to find the cart properly), payment is stuck "uncaptured".

We have some stores sharing Stripe credentials and other stores using different credentials (due to them being different legal entities). Since the fix in the latest version that allows us to register webhooks properly in a multistore environment has been applied, all webhooks were rebuilt from the module, but it seems they still don't work properly, or at least the store context is wrong when they are called (= cart not found).

**Comment by clotairer** [comment]
We publish the fix on release 2.4.0.

You can update your addon. If you have any trouble do not hesitate to contact our technical support here : https://addons.prestashop.com/en/contact-us?id_product=24922
